apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: daoistw/customer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL_PLACEHOLDER
              value: jdbc:postgresql://lin-17794-6089-pgsql-primary.servers.linodedb.net:5432/customer
          envFrom:
            - configMapRef:
                name: postgres-credentials
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer