apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: daoistw/notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_URL_PLACEHOLDER
              value: jdbc:postgresql://postgres/notification
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: kafka:9092
          envFrom:
            - configMapRef:
                name: postgres-credentials
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification