apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 1
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: daoistw/fraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_URL_PLACEHOLDER
              value: jdbc:postgresql://postgres/fraud
          envFrom:
            - configMapRef:
                name: postgres-credentials
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraud