server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411/

eureka:
  client:
    enabled: false
    fetch-registry: false
    register-with-eureka: false